version: '3.1'

services:
  reader:
    container_name: reader
    build: ./reader
    restart: always
    ports:
      - "5005:5005"
    depends_on:
      - writer
    links:
     - writer
  writer:
    container_name: writer
    build: ./writer
    restart: always
    ports:
      - "5001:5001"
    depends_on:
      - db
    links:
     - db
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: patrick
      POSTGRES_PASSWORD: "erasmusmundus"
      POSTGRES_DB: ciklum
    ports:
      - "5050:5432"
    logging:
      driver: none